# Seata client early FileConfiguration (classpath:file.conf)
service {
  vgroupMapping.simlect_tx_group = "default"
  vgroupMapping.default_tx_group = "default"
  default.grouplist = "127.0.0.1:8091"
  enableDegrade = false
  disable = false
}
